export const mockModules = [
  {
    _id: "mod-1",
    title: "Greetings in ISL",
    titleHi: "ISL में अभिवादन",
    description: "Learn basic greeting signs",
    category: "Greetings",
    videoUrl: "",
    question: "How do you say 'Namaste' in ISL?",
    questionHi: "ISL में 'नमस्ते' कैसे कहते हैं?",
    options: ["Open palm raised", "Fist bump", "Wave hand", "Point finger"],
    optionsHi: ["खुला हाथ उठाना", "मुक्का टकराना", "हाथ हिलाना", "उंगली इंगित करना"],
    correctAnswer: "Open palm raised",
    active: true,
    order: 1,
    difficulty: "beginner",
    estimatedMinutes: 3,
    signsIncluded: ["namaste", "thank-you", "sorry", "please"],
    serviceRelevance: ["general"],
  },
  {
    _id: "mod-2",
    title: "Numbers & Counting",
    titleHi: "संख्या और गिनती",
    description: "Learn numbers 1-10 in ISL",
    category: "Numbers",
    videoUrl: "",
    question: "Which hand shape represents '5' in ISL?",
    questionHi: "ISL में '5' का प्रतीक कौन सा हाथ है?",
    options: ["Open palm, all fingers", "Closed fist", "Two fingers", "Thumb up"],
    optionsHi: ["खुली हथेली, सभी उंगलियां", "बंद मुक्का", "दो उंगलियां", "अंगूठा ऊपर"],
    correctAnswer: "Open palm, all fingers",
    active: true,
    order: 2,
    difficulty: "beginner",
    estimatedMinutes: 3,
    signsIncluded: ["one", "two", "three", "four", "five"],
    serviceRelevance: ["general", "payments"],
  },
  {
    _id: "mod-3",
    title: "Water Tax Vocabulary",
    titleHi: "जल कर शब्दावली",
    description: "Essential signs for water tax counter",
    category: "Services",
    videoUrl: "",
    question: "What is the ISL sign for 'Water'?",
    questionHi: "'पानी' का ISL संकेत क्या है?",
    options: ["Wiggle fingers downward like rain", "Point to mouth", "Make a cup shape", "Clap hands"],
    optionsHi: ["बारिश की तरह नीचे उंगलियां हिलाएं", "मुंह की ओर इंगित करें", "कप का आकार बनाएं", "ताली बजाएं"],
    correctAnswer: "Wiggle fingers downward like rain",
    active: true,
    order: 3,
    difficulty: "beginner",
    estimatedMinutes: 3,
    signsIncluded: ["water", "bill", "payment", "tax", "help"],
    serviceRelevance: ["water-tax", "payments"],
  },
  {
    _id: "mod-4",
    title: "Document Signs",
    titleHi: "दस्तावेज़ संकेत",
    description: "Learn signs for document-related interactions",
    category: "Documents",
    videoUrl: "",
    question: "How do you sign 'Certificate' in ISL?",
    questionHi: "ISL में 'प्रमाणपत्र' कैसे साइन करते हैं?",
    options: ["Make a rectangular shape with hands", "Point downward", "Cross fingers", "Open palms up"],
    optionsHi: ["हाथों से आयताकार आकार बनाएं", "नीचे इंगित करें", "उंगलियां क्रॉस करें", "हथेलियां ऊपर खोलें"],
    correctAnswer: "Make a rectangular shape with hands",
    active: true,
    order: 4,
    difficulty: "beginner",
    estimatedMinutes: 3,
    signsIncluded: ["certificate", "form", "document", "name", "address"],
    serviceRelevance: ["certificates", "documents"],
  },
  {
    _id: "mod-5",
    title: "Emergency Signs",
    titleHi: "आपातकालीन संकेत",
    description: "Critical emergency and help signs",
    category: "Emergency",
    videoUrl: "",
    question: "What is the ISL sign for 'Help'?",
    questionHi: "'मदद' का ISL संकेत क्या है?",
    options: ["Fist on open palm, push forward", "Wave both hands", "Point to self", "Snap fingers"],
    optionsHi: ["खुली हथेली पर मुक्का, आगे धकेलें", "दोनों हाथ हिलाएं", "अपनी ओर इंगित करें", "उंगलियों से क्लिक करें"],
    correctAnswer: "Fist on open palm, push forward",
    active: true,
    order: 5,
    difficulty: "beginner",
    estimatedMinutes: 3,
    signsIncluded: ["help", "hospital", "police", "emergency"],
    serviceRelevance: ["complaints", "emergency"],
  },
];
