export const mockUsers = [
  {
    _id: "demo-clerk-1",
    username: "ramesh",
    name: "Ramesh Patel",
    department: "Water Services",
    role: "clerk" as const,
    designation: "Senior Clerk",
    employeeId: "EMP-001",
    city: "Vadodara",
    state: "Gujarat",
    language: "en" as const,
    status: "active" as const,
    currentStreak: 12,
    longestStreak: 18,
    totalCompleted: 45,
    lastCompletedDate: new Date().toISOString().split("T")[0],
    isChampion: true,
    islXp: 920,
    islLevel: 10,
    islStreak: 12,
    islBadges: ["first-sign", "7-day-streak", "counter-ready", "100-xp"],
    islSignsCompleted: ["water", "bill", "payment", "tax", "yes", "no", "wait", "help", "namaste", "thank-you"],
  },
  {
    _id: "demo-clerk-2",
    username: "sita",
    name: "Sita Sharma",
    department: "Citizen Certificates",
    role: "clerk" as const,
    designation: "Junior Clerk",
    employeeId: "EMP-002",
    city: "Vadodara",
    state: "Gujarat",
    language: "hi" as const,
    status: "active" as const,
    currentStreak: 8,
    longestStreak: 14,
    totalCompleted: 32,
    lastCompletedDate: new Date().toISOString().split("T")[0],
    isChampion: false,
    islXp: 870,
    islLevel: 9,
    islStreak: 8,
    islBadges: ["first-sign", "7-day-streak", "100-xp"],
    islSignsCompleted: ["certificate", "form", "name", "address", "yes", "no", "please"],
  },
  {
    _id: "demo-clerk-3",
    username: "amit",
    name: "Amit Shah",
    department: "Property Services",
    role: "clerk" as const,
    designation: "Clerk",
    employeeId: "EMP-003",
    city: "Ahmedabad",
    state: "Gujarat",
    language: "en" as const,
    status: "active" as const,
    currentStreak: 5,
    longestStreak: 10,
    totalCompleted: 20,
    lastCompletedDate: new Date().toISOString().split("T")[0],
    isChampion: false,
    islXp: 810,
    islLevel: 9,
    islStreak: 5,
    islBadges: ["first-sign", "100-xp"],
    islSignsCompleted: ["document", "tax", "payment", "yes", "no"],
  },
  {
    _id: "demo-clerk-4",
    username: "neha",
    name: "Neha Joshi",
    department: "Water Services",
    role: "clerk" as const,
    designation: "Junior Clerk",
    employeeId: "EMP-004",
    city: "Mumbai",
    state: "Maharashtra",
    language: "mr" as const,
    status: "active" as const,
    currentStreak: 3,
    longestStreak: 7,
    totalCompleted: 15,
    lastCompletedDate: new Date().toISOString().split("T")[0],
    isChampion: false,
    islXp: 450,
    islLevel: 7,
    islStreak: 3,
    islBadges: ["first-sign"],
    islSignsCompleted: ["water", "bill", "yes", "no", "help"],
  },
  {
    _id: "demo-admin-1",
    username: "admin",
    name: "System Administrator",
    department: "Administration",
    role: "super_admin" as const,
    designation: "Super Admin",
    employeeId: "ADM-001",
    city: "New Delhi",
    state: "Delhi",
    language: "en" as const,
    status: "active" as const,
    currentStreak: 0,
    longestStreak: 0,
    totalCompleted: 0,
    isChampion: false,
    islXp: 0,
    islLevel: 1,
    islStreak: 0,
    islBadges: [],
    islSignsCompleted: [],
  },
  {
    _id: "demo-admin-2",
    username: "wateradmin",
    name: "Water Dept Admin",
    department: "Water Services",
    role: "dept_admin" as const,
    designation: "Department Head",
    employeeId: "ADM-002",
    city: "Vadodara",
    state: "Gujarat",
    language: "en" as const,
    status: "active" as const,
    currentStreak: 0,
    longestStreak: 0,
    totalCompleted: 0,
    isChampion: false,
    islXp: 0,
    islLevel: 1,
    islStreak: 0,
    islBadges: [],
    islSignsCompleted: [],
  },
];

export function findMockUser(username: string) {
  return mockUsers.find((u) => u.username === username.toLowerCase());
}

export function getMockLeaderboard() {
  return mockUsers
    .filter((u) => u.role === "clerk")
    .sort((a, b) => b.islXp - a.islXp)
    .map((u, i) => ({
      rank: i + 1,
      username: u.username,
      name: u.name,
      department: u.department,
      islXp: u.islXp,
      islLevel: u.islLevel,
      currentStreak: u.currentStreak,
      isChampion: u.isChampion,
    }));
}
