export const MR: Record<string, string> = {
  "Learn Indian Sign Language": "भारतीय सांकेतिक भाषा शिका",
  "For citizens, by citizens. No login required.": "नागरिकांसाठी, नागरिकांद्वारे. लॉगिन आवश्यक नाही.",
  "levels completed": "स्तर पूर्ण",
  "Flashcards": "फ्लॅशकार्ड",
  "Flip cards to learn signs and their meanings": "चिन्हे आणि त्यांचे अर्थ जाणून घेण्यासाठी कार्डे फ्लिप करा",
  "Quiz Challenge": "क्विझ आव्हान",
  "Test your knowledge with quick quizzes": "द्रुत क्विझसह आपल्या ज्ञानाची चाचणी घ्या",
  "Use your camera to practice real signs": "वास्तविक चिन्हांचा सराव करण्यासाठी आपला कॅमेरा वापरा",
  "View All Badges": "सर्व बॅजेस पहा",
  "Level": "स्तर",
  "Day Streak": "दैनिक क्रम",
  "Accuracy": "अचूकता",
  "Badges": "बॅजेस",
  "Learned": "शिकलो",
  "Back to Home": "मुखपृष्ठावर परत",
  "Exit": "बाहेर",
  "Skip": "वगळा",
  "I Know This": "मला हे माहित आहे",
  "Tap to reveal meaning": "अर्थ प्रकट करण्यासाठी टॅप करा",
  "What does this sign mean?": "या चिन्हाचा अर्थ काय?",
  "Sign": "चिन्ह",
  "Correct": "बरोबर",
  "Incorrect": "चूक",
  "Next Question": "पुढील प्रश्न",
  "See Final Results": "अंतिम निकाल पहा",
  "Start Camera": "कॅमेरा सुरू करा",
  "Choose a sign to practice": "सरावासाठी एक चिन्ह निवडा",
  "Show the sign to your camera": "आपल्या कॅमेऱ्याला चिन्ह दाखवा",
  "Webcam Practice": "वेबकॅम सराव",
  "Practice Again": "पुन्हा सराव करा",
  "Done": "पूर्ण",
  "Achievements": "उपलब्धी",
  "unlocked": "अनलॉक",
  "of": "पैकी",
  "Search signs...": "चिन्हे शोधा...",
  "All Categories": "सर्व श्रेण्या",
  "Greetings": "अभिवादन",
  "Office & Services": "कार्यालय आणि सेवा",
  "Emergency & Help": "आपत्कालीन आणि मदत",
  "Daily Life": "दैनंदिन जीवन",
  "Numbers & Counting": "संख्या आणि मोजणी",
  "Question Words": "प्रश्न शब्द",
  "Dark Mode": "डार्क मोड",
  "Sound": "ध्वनी",
  "Leaderboard": "लीडरबोर्ड",
  "No results found": "कोणतेही परिणाम आढळले नाहीत",
  "Login": "लॉगिन",
  "Clerk Dashboard": "क्लार्क डॅशबोर्ड",
  "Your Streak": "आपला क्रम",
  "Best": "सर्वोत्तम",
  "Total": "एकूण",
  "Today's Lesson": "आजचा धडा",
  "Great work today!": "आजचे काम उत्तम!",
  "Correct!": "बरोबर!",
  "Not quite right": "बरोबर नाही",
  "Your Stats": "आपली आकडेवारी",
  "Current Streak": "सध्याचा क्रम",
  "Longest Streak": "सर्वात लांब क्रम",
  "Total Lessons": "एकूण धडे",
  "Open Camera Practice": "कॅमेरा सराव उघडा",
  "Sign practice completed!": "चिन्ह सराव पूर्ण!",
  "Download Certificate": "प्रमाणपत्र डाउनलोड करा",
  "No Lessons Available": "कोणतेही धडे उपलब्ध नाहीत",
  "ISL Dictionary": "ISL शब्दकोश",
  "Back": "मागे",
  "You scored": "तुम्ही गुण मिळवले",
  "across": "मध्ये",
  "categories": "श्रेण्या",
  "Sign Recognized!": "चिन्ह ओळखले गेले!",
  "You signed": "तुम्ही चिन्ह केले",
  "correctly!": "बरोबर!",
  "Starting camera...": "कॅमेरा सुरू होत आहे...",
  "Try Again": "पुन्हा प्रयत्न करा",
  "Practice count": "सराव संख्या",
  "per successful practice": "प्रति यशस्वी सराव",
  "Top ISL learners": "शीर्ष ISL शिकणारे",
  "streak": "क्रम",
  "Play ISL Quest": "ISL Quest खेळा",
  "View 12-Week Curriculum": "12-आठवड्याचा अभ्यासक्रम पहा",
  "DEAF PERSON IS SIGNING": "बधिर व्यक्ती संकेत करत आहे",
  "CLERK SEES": "क्लार्क पाहतो - नागरिक म्हणू इच्छितो:",
  "CLERK REPLIES": "क्लार्क उत्तर देतो",
};
